### ISSUE TITLE
Applying Deep Subspace Clustering to High Dimensional Data

### ISSUE THREAD

**Issue by ferrerorocher-gpu** [panji1990/Deep-subspace-clustering-networks#13]
Having reading through the paper, I have seen that the coding for the Autoencoder has been primarily done by using Convolutional Kernels since the paper had worked with Images.
I need your inputs on finding the subspace for Data for the following format : 
N Individual Datapoints each having 1-D dimension of size X (>100) i.e N separate data point of Array size (>100).
The Target is to Cluster these N data points into clusters.
Your inputs will be very helpful.

**Comment by panji530** [comment]
The simplest way would be to change the kernel size to 1x1.
