### ISSUE TITLE
Not able to reproduce results, Stopping pre-training for ORL dataset?

### ISSUE THREAD

**Issue by jeya-maria-jose** [panji1990/Deep-subspace-clustering-networks#14]
Hi
Can you please give an idea of around what epoch you stopped the pretraining for ORL dataset ? Even after following your way (early stopping at good visualizations) to stop pre-train, there is a huge variation in the result compared to restoring the pre-trained weights you have provided.

**Comment by panji530** [comment]
ORL dataset probably has too few samples for each class, so not good for subspace representation. I forgot to record the exact epoch for stop pertaining..., but I do remember I stopped the training quite arbitrarily, did not fine-tune it ...
