### ISSUE TITLE
How can I get the specific subspace?

### ISSUE THREAD

**Issue by HuaYZhao** [panji1990/Deep-subspace-clustering-networks#18]
How can I get the specific subspace?
I want to analyze the subspaces obtained by clustering. I hope I can get some guidance. I am very grateful！

**Comment by Xanadu12138** [comment]
For example, you can reshape label matrix to origianl data's shape as position matrix. And find data in same subspace corrsponding with the position matrix.

**Comment by HuaYZhao** [comment]
Sorry for the late reply. thx! I'll try it soon!
