### ISSUE TITLE
Can't find .ckpt file when call saver.restore

### ISSUE THREAD

**Issue by Raymongd007** [panji1990/Deep-subspace-clustering-networks#4]
I met a read problem when I call the function `restore()` in main function, the error message is like below,

` Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ~/Documents/DeepSubspace/Deep-subspace-clustering-networks-master/pretrain-model-COIL100/model50.ckpt
`

To my understanding, when you call `self.saver.restore(self.sess, self.model_path)`, actually you are loading the predefined model from directory, but I look into the model path, there is no file ends with .ckpt, which is the file type that the saver want for loading the variables, I'm wondering if you forget to upload the predefined model file?

**Comment by panji530** [comment]
Please make sure your model directory is updated to the folder where you put the models.
