### ISSUE TITLE
When does pre-training end?

### ISSUE THREAD

**Issue by yyl199655** [panji1990/Deep-subspace-clustering-networks#5]
When does pre-training end?

**Comment by panji530** [comment]
Please refer to the Readme file: "The key thing to take care of during pre-training is early-stop, which means you need stop training once the reconstructed images are reasonably good (visually)." So stop the training periodically and check the quality of reconstructed images (using test_face(Img, CAE, n_input)).

**Comment by jeya-maria-jose** [comment]
@panji1990  Is it possible to know the exact epoch at which the pre-training ends? The model seems to be too much dependent on the pretrained weights and it would be great if you could let us know where you stopped the training for the pre-trained weights given in this repo.
