### ISSUE TITLE
How to fix the N problem?

### ISSUE THREAD

**Issue by HolmesShuan** [panji1990/Deep-subspace-clustering-networks#8]
Hi~ Nice job, though,  after reading your paper, I have the same question as mentioned in NIPS Reviewer 2:

>  One of the drawbacks of the proposed approach is the fact that the number of weights between the middle layers of the network is $N^2$, given $N$ data points. Thus, it seems that the method will not be scalable to very large datasets.

Any idea how to fix it? Thanks in advance.

**Comment by panji530** [comment]
Thanks for your interests! We do have several follow-up works to address the scalability issue. One  published paper can be found here:
https://arxiv.org/abs/1811.01045 .
We will release other related works in the next few months. If you are interested, you can keep an eye on my webpage: https://sites.google.com/site/peterji1990 .
